[package]
name = "rust-rocksdb-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.electrs-rocksdb]
version = "0.15.0-e2"
default-features = false
features = ["zstd"]
